server:
  port: 8088
  servlet:
    session:
      timeout: 1800s

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 3600s
  main:
    banner-mode: console
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    name: datasource
    url: jdbc:mysql://localhost:3306/mi?serverTimezone=GMT%2b8
    username: root
    password: 970512
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  path: /base-web-log

# 应用信息
app:
  app-name: mi
  app-host: http://app.com
  allow-generate-api: true
  allow-cross-domain-access: true
  # 开发dev 测试test  生产 master
  env: dev

# 对象存储配置
cos:
  secretId: AKIDWjhU1HH3bhXy82E3f4tUptgBfBXfpzc2
  secretKey: NXUCf1FEm8PTIK50jDX0EEyRebHhtrZ2
  upload-endpoint: ap-shanghai
  download-endpoint: https://mi-1259640766.cos.ap-shanghai.myqcloud.com
  bucketName: mi-1259640766
  # 下载地址的有效时长，单位为ms，默认为半小时
  download-url-expiration: 1800000
  #样式
#  styleName: resize,h_250
